"""remember trace ids

Revision ID: 9b5f5f45b925
Revises: c8aabe0fadb5
Create Date: 2025-04-22 20:45:49.593526

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b5f5f45b925"
down_revision: str | None = "c8aabe0fadb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("openai_trace_id", sa.String(), nullable=True))
    op.drop_index("ix_sessions_session_uuid", table_name="sessions")
    op.create_index(
        op.f("ix_sessions_session_uuid"), "sessions", ["session_uuid"], unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_session_uuid"), table_name="sessions")
    op.create_index(
        "ix_sessions_session_uuid", "sessions", ["session_uuid"], unique=False,
    )
    op.drop_column("sessions", "openai_trace_id")
    # ### end Alembic commands ###
