"""initial commit

Revision ID: c8aabe0fadb5
Revises:
Create Date: 2025-04-22 15:37:15.005773

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8aabe0fadb5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table first since it has no dependencies
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_logged_in", sa.Boolean(), nullable=False),
        sa.Column("user_type", sa.String(), nullable=False),
        sa.Column("user_permissions", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    
    # Create sessions table without the head_turn_id foreign key initially
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("head_turn_id", sa.Integer(), nullable=True),
        sa.Column("session_uuid", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_sessions_session_uuid"), "sessions", ["session_uuid"], unique=False,
    )
    
    # Create dialogue_turns table with session_id foreign key
    op.create_table(
        "dialogue_turns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=False),
        sa.Column("request_text", sa.String(), nullable=False),
        sa.Column(
            "response_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True,
        ),
        sa.Column("previous_turn_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["previous_turn_id"],
            ["dialogue_turns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dialogue_turns_correlation_id"),
        "dialogue_turns",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dialogue_turns_id"), "dialogue_turns", ["id"], unique=False,
    )
    
    # Add the head_turn_id foreign key to sessions table after dialogue_turns exists
    op.create_foreign_key(
        "fk_sessions_head_turn_id",
        "sessions",
        "dialogue_turns",
        ["head_turn_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key constraint first
    op.drop_constraint("fk_sessions_head_turn_id", "sessions", type_="foreignkey")
    
    op.drop_index(op.f("ix_dialogue_turns_id"), table_name="dialogue_turns")
    op.drop_index(op.f("ix_dialogue_turns_correlation_id"), table_name="dialogue_turns")
    op.drop_table("dialogue_turns")
    
    op.drop_index(op.f("ix_sessions_session_uuid"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_table("sessions")
    
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
